version: "3.9"

services:
    app:
        image: php:8.3-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: base-code-inertia-flowbite-react-js
            MYSQL_ROOT_PASSWORD: "" # root password kosong
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    node:
        image: node:22-alpine
        container_name: laravel_node_build
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: sh -c "npm install && npm run build"
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
        driver: bridge
